### ISSUE TITLE
parse_data() failing on mopak

### ISSUE THREAD

**Issue by rsignell-usgs** [ooi-integration/cgsn-parsers#8]
@cwingard, I updated to use the latest from master branch (thanks!), and I get further in my attempt to read the mopak binary files, but parse_data() is failing in cell [8] here:
http://nbviewer.jupyter.org/gist/rsignell-usgs/13d4231c83b2346c70c4c0e680d2d0e7

**Comment by cwingard** [comment]
That would be because you are using splitlines in your assignment of the binary data to the raw data object. Binary data needs to be left "whole", as a single "blob". Probably not using the right terminology there, but see the following for how to read in the binary mopak data:

http://nbviewer.jupyter.org/github/cwingard/cgsn-parsers/blob/books/notebooks/read_mopak.ipynb

Also, the variable time that gets created by the parser is the epoch time stamp (Seconds since 1970-01-01) derived from the date and time string associated with the files. You should use that value to assign time in the pandas (pd.to_datetime(df.time, unit='s'). All parsed data will have 'time', but not all data files will have a dcl_date_time_string or equivalent.

**Comment by rsignell-usgs** [comment]
@cwingard, thanks.  I'll take a look this weekend!

**Comment by rsignell-usgs** [comment]
Thanks!  Working now:
http://nbviewer.jupyter.org/gist/rsignell-usgs/13d4231c83b2346c70c4c0e680d2d0e7?flush_cache=true
