### ISSUE TITLE
HEX parser notebook example

### ISSUE THREAD

**Issue by rsignell-usgs** [ooi-integration/cgsn-parsers#9]
Write a notebook showing a HEX parser in action.  

According to @cwingard , "HEX files would be any of the SAMI's (PHSEN or PCO2W)."

**Comment by rsignell-usgs** [comment]
Okay, here's an example using Ph Sensor data:
http://nbviewer.jupyter.org/gist/rsignell-usgs/fcef1d2b7483159f59907da5830de5e0?flush_cache=True

@cwingard, there are several variables that end up having objects that are lists at each time step.  For example the light has 92 values at each time step.    In the example above, I just selected one of these values arbitrarily to make a time series plot.  

Are these different wavelengths?

Also, do you think these notebook examples should be in a directory in this repo, perhaps in 
https://github.com/ooi-integration/cgsn-parsers/notebooks  ??

If so, I can start issuing pull requests.

**Comment by rsignell-usgs** [comment]
Hmm, one more issue.   I tried switching this example to use the Pioneer data
```
# Coastal Pioneer - Central Surface Mooring
baseurl = "https://rawdata.oceanobservatories.org/files/CP01CNSM/D00006/cg_data/dcl26/phsen1/"
fname = "20170116.phsen1.log"
```
 instead of Endurance data 
```
#Coastal Endurance - WA Shelf Surface Piercing Profiler Mooring
baseurl = "https://rawdata.oceanobservatories.org/files/CE07SHSM/D00003/cg_data/dcl26/phsen1/"
fname = "20160926.phsen1.log"
```
and the parser failed.

**Comment by cwingard** [comment]
I already have started a notebook directory in the current branch I'm working on to, so yes, I think the notebooks are useful.

I'll look into the Pioneer example soon. I'm not as familiar with their data, and sometimes instruments have been configured differently.

**Comment by rsignell-usgs** [comment]
cool, thanks Chris!

**Comment by cwingard** [comment]
I finally had a chance to look into why my phsen parser code was failing on the Pioneer data file you pointed to.

The parser is working fine. It is returning an empty data set because something weird is happening with that SAMI and the first part of the data sentence is not being recorded.

Looks like it started happening on 2016-11-04 at 02:00 with a clock step/jump. Seems to bounce around for a few more days between complete/incomplete records before finally failing altogether. 

I ran your notebook example with a file earlier in the cruise and got good data.
